// smtp_tls_server.h - a scriptable in-process SMTP server that can speak TLS,
// either from the first byte (implicit TLS, what port 465 expects) or
// negotiated mid-conversation after a STARTTLS command (what port 587
// expects).
//
// Reused from smtp_server.h's design: a queue of replies handed out one per
// command, with the same DATA and script-exhaustion handling. The one thing
// this adds is a "channel" that can be a raw socket or an SSL connection, and
// switches from the former to the latter the moment it sends the reply to a
// STARTTLS command -- which is the same order of operations a real server
// follows, and lets one script exercise the whole upgrade without special
// casing it.
//
// Certificate and key are read from cert.pem / key.pem in the working
// directory, generated by the test with the openssl CLI the same way
// rudesocket's test_ssl_upgrade.cpp does.
#ifndef RUDESMTP_TESTS_SMTP_TLS_SERVER_H
#define RUDESMTP_TESTS_SMTP_TLS_SERVER_H

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <winsock2.h>
#include <ws2tcpip.h>
typedef SOCKET net_socket_t;
#define NET_INVALID_SOCKET INVALID_SOCKET
inline void net_close(net_socket_t s)
{
	closesocket(s);
}
#ifndef RUDESMTP_TESTS_NET_INIT_DEFINED
#define RUDESMTP_TESTS_NET_INIT_DEFINED
inline void net_init()
{
	WSADATA wsadata;
	WSAStartup(MAKEWORD(2, 2), &wsadata);
}
inline void net_cleanup()
{
	WSACleanup();
}
#endif
#else
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>
typedef int net_socket_t;
#define NET_INVALID_SOCKET (-1)
inline void net_close(net_socket_t s)
{
	::close(s);
}
#ifndef RUDESMTP_TESTS_NET_INIT_DEFINED
#define RUDESMTP_TESTS_NET_INIT_DEFINED
inline void net_init() {}
inline void net_cleanup() {}
#endif
#endif

#include <openssl/err.h>
#include <openssl/ssl.h>

#include <cstdio>
#include <unistd.h>
#include <cstring>
#include <string>
#include <vector>

class SmtpTlsServer
{
	net_socket_t d_listen;
	int d_port;

	// If true, the handshake happens immediately on accept, before the
	// greeting -- implicit TLS. If false, the connection starts in the
	// clear and upgrades when a STARTTLS command is seen.
	bool d_immediateTls;

	std::string d_greeting;
	std::vector<std::string> d_replies;
	size_t d_next;
	std::vector<std::string> d_received;

	// The size of d_received at the moment the handshake completed, so a
	// caller can tell which lines arrived in the clear from which arrived
	// over TLS -- checking the whole list for a given command would always
	// find it if it was sent at all, encrypted or not.
	size_t d_receivedAtUpgrade;

	// Whether verification would succeed is entirely up to the client;
	// this server always presents the same self-signed certificate.
	bool d_handshook;

	SSL_CTX *d_ctx;
	SSL *d_ssl;			// non-null once upgraded
	net_socket_t d_raw; // the accepted connection

	bool rawSend(const std::string &text)
	{
		size_t off = 0;
		while(off < text.size())
		{
			const int sent = (int) ::send(d_raw, text.data() + off, (int) (text.size() - off), 0);
			if(sent <= 0)
			{
				return false;
			}
			off += (size_t) sent;
		}
		return true;
	}

	bool sslSend(const std::string &text)
	{
		size_t off = 0;
		while(off < text.size())
		{
			const int sent = SSL_write(d_ssl, text.data() + off, (int) (text.size() - off));
			if(sent <= 0)
			{
				return false;
			}
			off += (size_t) sent;
		}
		return true;
	}

	// Sends over whichever channel is currently active.
	bool chanSend(const std::string &text)
	{
		return d_ssl ? sslSend(text) : rawSend(text);
	}

	// Reads one CRLF-terminated line over whichever channel is active.
	// Returns false at EOF.
	bool chanReadLine(std::string &out)
	{
		out.clear();
		for(;;)
		{
			char c;
			const int rc = d_ssl ? SSL_read(d_ssl, &c, 1) : (int) ::recv(d_raw, &c, 1, 0);
			if(rc <= 0)
			{
				return !out.empty();
			}
			if(c == '\n')
			{
				return true;
			}
			if(c != '\r')
			{
				out += c;
			}
		}
	}

	// Wraps the raw connection in TLS. On success d_ssl becomes non-null
	// and chanSend()/chanReadLine() switch to it from here on.
	bool upgrade()
	{
		d_ctx = SSL_CTX_new(TLS_server_method());
		if(!d_ctx)
		{
			return false;
		}
		if(SSL_CTX_use_certificate_file(d_ctx, "cert.pem", SSL_FILETYPE_PEM) <= 0 ||
		   SSL_CTX_use_PrivateKey_file(d_ctx, "key.pem", SSL_FILETYPE_PEM) <= 0)
		{
			std::fprintf(stderr, "server: could not load cert.pem/key.pem\n");
			return false;
		}
		d_ssl = SSL_new(d_ctx);
		SSL_set_fd(d_ssl, (int) d_raw);
		if(SSL_accept(d_ssl) != 1)
		{
			std::fprintf(stderr, "server: SSL_accept failed\n");
			ERR_print_errors_fp(stderr);
			SSL_free(d_ssl);
			d_ssl = 0;
			return false;
		}
		d_handshook = true;
		d_receivedAtUpgrade = d_received.size();
		return true;
	}

  public:
	SmtpTlsServer(bool immediateTls)
		: d_listen(NET_INVALID_SOCKET), d_port(0), d_immediateTls(immediateTls), d_greeting("220 test.example.com ESMTP\r\n"), d_next(0), d_receivedAtUpgrade(0), d_handshook(false), d_ctx(0), d_ssl(0), d_raw(NET_INVALID_SOCKET)
	{
		d_listen = ::socket(AF_INET, SOCK_STREAM, 0);
		sockaddr_in addr;
		std::memset(&addr, 0, sizeof(addr));
		addr.sin_family = AF_INET;
		addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
		addr.sin_port = 0;
		::bind(d_listen, (sockaddr *) &addr, sizeof(addr));
		::listen(d_listen, 1);
		socklen_t len = sizeof(addr);
		::getsockname(d_listen, (sockaddr *) &addr, &len);
		d_port = ntohs(addr.sin_port);
	}

	~SmtpTlsServer()
	{
		if(d_ssl)
		{
			SSL_free(d_ssl);
		}
		if(d_ctx)
		{
			SSL_CTX_free(d_ctx);
		}
		if(d_raw != NET_INVALID_SOCKET)
		{
			net_close(d_raw);
		}
		if(d_listen != NET_INVALID_SOCKET)
		{
			net_close(d_listen);
		}
	}

	int port() const
	{
		return d_port;
	}

	void setGreeting(const std::string &greeting)
	{
		d_greeting = greeting;
	}

	void addReply(const std::string &reply)
	{
		d_replies.push_back(reply);
	}

	bool handshook() const
	{
		return d_handshook;
	}

	const std::vector<std::string> &received() const
	{
		return d_received;
	}

	// True if any line received BEFORE the handshake started with prefix.
	// This is what "was this sent in the clear" actually means -- checking
	// the whole received() list would always find a command that was sent
	// at all, whichever channel it went over.
	bool sawInClearWithPrefix(const std::string &prefix) const
	{
		for(size_t i = 0; i < d_receivedAtUpgrade && i < d_received.size(); i++)
		{
			if(d_received[i].compare(0, prefix.size(), prefix) == 0)
			{
				return true;
			}
		}
		return false;
	}

	bool sawLine(const std::string &line) const
	{
		for(size_t i = 0; i < d_received.size(); i++)
		{
			if(d_received[i] == line)
			{
				return true;
			}
		}
		return false;
	}

	void run()
	{
		d_raw = ::accept(d_listen, 0, 0);
		if(d_raw == NET_INVALID_SOCKET)
		{
			return;
		}

		if(d_immediateTls)
		{
			if(!upgrade())
			{
				net_close(d_raw);
				d_raw = NET_INVALID_SOCKET;
				return;
			}
		}

		if(!d_greeting.empty())
		{
			chanSend(d_greeting);
		}

		bool inData = false;
		for(;;)
		{
			std::string line;
			if(!chanReadLine(line))
			{
				break;
			}
			d_received.push_back(line);

			if(inData)
			{
				if(line == ".")
				{
					inData = false;
				}
				else
				{
					continue;
				}
			}
			else if(line.size() >= 4 && line.compare(0, 4, "DATA") == 0)
			{
				if(d_next < d_replies.size() && d_replies[d_next].compare(0, 3, "354") == 0)
				{
					inData = true;
				}
			}

			if(d_next >= d_replies.size())
			{
				break;
			}

			const std::string reply = d_replies[d_next++];
			if(!chanSend(reply))
			{
				break;
			}

			// The handshake happens right after the reply that invites it,
			// matching what a real server does: STARTTLS's "220 go ahead"
			// is the last thing said in the clear.
			if(!d_immediateTls && !d_ssl && line.size() >= 8 && line.compare(0, 8, "STARTTLS") == 0 && reply.compare(0, 3, "220") == 0)
			{
				if(!upgrade())
				{
					break;
				}
			}
		}

		net_close(d_raw);
		d_raw = NET_INVALID_SOCKET;
	}
};

#endif
